# prompts.py
from langchain_core.prompts import PromptTemplate


    
# RunnableBranch Prompts
    
# FR-4: Each branch uses a specialised PromptTemplate.
    


programming_prompt = PromptTemplate(
    input_variables=["question"],
    template=(
        "You are an expert Programming Assistant.\n\n"
        "Your task is to answer programming-related questions "
        "accurately and practically.\n"
        "Explain the concept clearly.\n"
        "When appropriate, provide a short and useful code example.\n"
        "If the question contains an error or bug, explain the cause "
        "and provide a corrected approach.\n\n"
        "User question:\n"
        "{question}\n\n"
        "Answer:"
    ),
)


math_prompt = PromptTemplate(
    input_variables=["question"],
    template=(
        "You are a patient and precise Mathematics Tutor.\n\n"
        "Solve the user's mathematics problem clearly.\n"
        "Show the important steps used to reach the solution.\n"
        "Use appropriate mathematical notation where helpful.\n"
        "Clearly identify the final result at the end.\n\n"
        "User question:\n"
        "{question}\n\n"
        "Answer:"
    ),
)


general_prompt = PromptTemplate(
    input_variables=["question"],
    template=(
        "You are a helpful General Assistant.\n\n"
        "Answer the user's question accurately, clearly, and "
        "concisely.\n"
        "Use simple explanations when possible.\n"
        "If the question requires multiple points, organize the "
        "answer logically.\n\n"
        "User question:\n"
        "{question}\n\n"
        "Answer:"
    ),
)


    
# RunnableParallel Prompts
    
# FR-5: These prompts operate on the answer generated by RunnableBranch.
#
# The parallel stage receives:
#
#     {
#         "question": ...,
#         "category": ...,
#         "answer": ...
#     }
#
# Each independent pipeline below uses the routed answer.
    


summary_prompt = PromptTemplate(
    input_variables=["answer"],
    template=(
        "Summarize the following chatbot answer in one or two "
        "clear sentences.\n\n"
        "Answer:\n"
        "{answer}\n\n"
        "Summary:"
    ),
)


keywords_prompt = PromptTemplate(
    input_variables=["answer"],
    template=(
        "Extract 3 to 6 important keywords or short key phrases "
        "from the following chatbot answer.\n\n"
        "Return ONLY the keywords as a comma-separated list.\n"
        "Do not add explanations, numbering, or extra text.\n\n"
        "Answer:\n"
        "{answer}\n\n"
        "Keywords:"
    ),
)


followup_prompt = PromptTemplate(
    input_variables=["answer"],
    template=(
        "Suggest one natural and useful follow-up question that "
        "the user could ask after reading the following answer.\n\n"
        "Return ONLY the follow-up question.\n"
        "Do not add explanations or additional text.\n\n"
        "Answer:\n"
        "{answer}\n\n"
        "Follow-up question:"
    ),
)


    
# Final Pydantic Structuring Prompt
    
# FR-3: The intermediate outputs are combined here and passed to
# llm.with_structured_output(ChatResponse).
    


structuring_prompt = PromptTemplate(
    input_variables=[
        "question",
        "category",
        "answer",
        "summary",
        "keywords",
        "followup",
    ],
    template=(
        "You are the final response formatter for a chatbot.\n\n"
        "Use the information produced by the previous pipeline "
        "stages to create a clean and validated chatbot response.\n\n"

        "Original question:\n"
        "{question}\n\n"

        "Detected category:\n"
        "{category}\n\n"

        "Main answer:\n"
        "{answer}\n\n"

        "Draft summary:\n"
        "{summary}\n\n"

        "Draft keywords:\n"
        "{keywords}\n\n"

        "Draft follow-up question:\n"
        "{followup}\n\n"

        "Create the final structured response with the following "
        "requirements:\n\n"

        "1. answer:\n"
        "   Provide a polished and complete version of the main answer.\n\n"

        "2. summary:\n"
        "   Provide a concise one-to-two sentence summary.\n\n"

        "3. category:\n"
        "   Use the detected category exactly as provided.\n\n"

        "4. keywords:\n"
        "   Return 3 to 6 clean and relevant keyword strings.\n\n"

        "5. confidence:\n"
        "   Provide a confidence score between 0 and 1 based on how "
        "reliable and complete the answer is.\n\n"

        "6. follow_up_question:\n"
        "   Provide one natural follow-up question based on the "
        "user's original question and the answer."
    ),
)

